export type Variant =
  | "primary"
  | "secondary"
  | "accent"
  | "info"
  | "success"
  | "warning"
  | "error"
  | "primary-bg-gradient"
  | "primary-gradient"
  | "secondary-gradient"
  | "turquoise-gradient"
  | "magenta-gradients"
  | "orange-gradient"
  | "light-purple-gradient"
  | "light-blue-gradient"
  | "light-orange-gradient"
  | "white";
